apiVersion: apps/v1
kind: Deployment
metadata:
  name: assignment3-django-deploy
  labels:
    app: assignment3-django-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      pod: assignment3-django-deploy
  template:
    metadata:
      labels:
        pod: assignment3-django-deploy
    spec:
      containers:
        - name: assignment3-django-deploy
          image: nyuappsec/assign3:v0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_ROOT_PASSWORD

            - name: MYSQL_DB
              value: GiftcardSiteDB

            - name: MYSQL_HOST
              value: mysql-service

            - name: ALLOWED_HOSTS
              value: "*,"

            - name: DJANGO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: django-secret
                  key: DJANGO_SECRET_KEY

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: 20
            periodSeconds: 30
            timeoutSeconds: 2
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 15
            timeoutSeconds: 2
            failureThreshold: 3

          volumeMounts:
            - name: mysql-volume-mount
              mountPath: /var/lib/busybox

            - name: static-data-volume-mount
              mountPath: /vol/static

      volumes:
        - name: mysql-volume-mount
          persistentVolumeClaim:
            claimName: mysql-pvc

        - name: static-data-volume-mount
          persistentVolumeClaim:
            claimName: static-data-pvc